library(caret)
FBI_APPLE1=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE1.csv",stringsAsFactors = FALSE)
FBI_APPLE2=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE2.csv",stringsAsFactors = FALSE)
FBI_APPLE3=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE3.csv",stringsAsFactors = FALSE)
FBI_APPLE4=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE4.csv",stringsAsFactors = FALSE)
dim(FBI_APPLE1)
dim(FBI_APPLE2)
dim(FBI_APPLE3)
dim(FBI_APPLE4)
#FBI-APPLE_sample=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Scripts/FBI-APPLE_1000.csv",stringsAsFactors = FALSE)
FBI_APPLE=rbind(FBI_APPLE1,FBI_APPLE2,FBI_APPLE3,FBI_APPLE4)
#dim(FBI_APPLE_sample)
dim(FBI_APPLE)
FBI_APPLE$TweetID=1:nrow(FBI_APPLE)
FBI_APPLE_merge=left_join(FBI_APPLE,FBI_APPLE_sample,by="TweetID",copy=TRUE)
FBI_APPLE$Topic=FBI_APPLE_merge$Topic
FBI_APPLE$Topic=tolower(FBI_APPLE$Topic)
FBI_APPLE_tagged=FBI_APPLE[!is.na(FBI_APPLE$Topic),]
dim(FBI_APPLE_tagged)
FBI_APPLE_untagged=FBI_APPLE[is.na(FBI_APPLE$Topic),]
dim(FBI_APPLE_untagged)



FBI_APPLE1$TweetID=1:nrow(FBI_APPLE1)
FBI_APPLE2$TweetID=(nrow(FBI_APPLE1)+1):(nrow(FBI_APPLE1)+nrow(FBI_APPLE2))
FBI_APPLE3$TweetID=(nrow(FBI_APPLE1)+nrow(FBI_APPLE2)+1):(nrow(FBI_APPLE1)+nrow(FBI_APPLE2)+nrow(FBI_APPLE3))
FBI_APPLE4$TweetID=(nrow(FBI_APPLE1)+nrow(FBI_APPLE2)+nrow(FBI_APPLE3)+1):(nrow(FBI_APPLE1)+nrow(FBI_APPLE2)+nrow(FBI_APPLE3)+nrow(FBI_APPLE4))

FBI_APPLEInd=createDataPartition(FBI_APPLE$Category,p=(999/nrow(FBI_APPLE)),list=FALSE)
length(FBI_APPLEInd)
FBI_APPLE2Ind=createDataPartition(FBI_APPLE2$Category,p=(249/nrow(FBI_APPLE2)),list=FALSE)
length(FBI_APPLE2Ind)
FBI_APPLE3Ind=createDataPartition(FBI_APPLE3$Category,p=(249/nrow(FBI_APPLE3)),list=FALSE)
length(FBI_APPLE3Ind)
FBI_APPLE4Ind=createDataPartition(FBI_APPLE4$Category,p=(248/nrow(FBI_APPLE4)),list=FALSE)
length(FBI_APPLE4Ind)
FBI_APPLE_1000=FBI_APPLE[FBI_APPLEInd,]
FBI_APPLE2_250=FBI_APPLE2[FBI_APPLE2Ind,]
FBI_APPLE3_250=FBI_APPLE3[FBI_APPLE3Ind,]
FBI_APPLE4_250=FBI_APPLE4[FBI_APPLE4Ind,]
table(FBI_APPLE_1000$Category)
table(FBI_APPLE2_250$Category)
table(FBI_APPLE3_250$Category)
table(FBI_APPLE4_250$Category)
FBI_APPLE_1000=rbind(FBI_APPLE1_250,FBI_APPLE2_250,FBI_APPLE3_250,FBI_APPLE4_250)
table(FBI_APPLE_1000$Category)
write.csv(FBI_APPLE_1000,"FBI_APPLE_1000.csv",row.names = FALSE)




########## creating full datasets
FBI_APPLE1=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE1.csv",stringsAsFactors = FALSE)
FBI_APPLE2=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE2.csv",stringsAsFactors = FALSE)
FBI_APPLE3=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE3.csv",stringsAsFactors = FALSE)
FBI_APPLE4=read.csv("C:/Users/Jay/Desktop/Prof.Mike/FBI-APPLE/FBI-APPLE4.csv",stringsAsFactors = FALSE)
dim(FBI_APPLE1)
dim(FBI_APPLE2)
dim(FBI_APPLE3)
dim(FBI_APPLE4)
#FBI-APPLE_sample=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Scripts/FBI-APPLE_1000.csv",stringsAsFactors = FALSE)
FBI_APPLE=rbind(FBI_APPLE1,FBI_APPLE2,FBI_APPLE3,FBI_APPLE4)
#dim(FBI_APPLE_sample)
dim(FBI_APPLE)
### Extracting Hashtags,@ and URLs into seperate columns.
library(stringr)
hashtag.regex <- regex("(?<=^|\\s)#\\S+")
attag.regex<-regex("(?<=^|\\s)@\\S+")
url.regex<-regex("http[^[:blank:]]+")
FBI_APPLE$Contents=tolower(FBI_APPLE$Contents)
hashtags <- str_extract_all(FBI_APPLE$Contents, hashtag.regex)
attags<-str_extract_all(FBI_APPLE$Contents, attag.regex)
urls<-str_extract_all(FBI_APPLE$Contents, url.regex)
rt_flag <- grepl("^RT",FBI_APPLE$Contents, ignore.case=TRUE)
Privacy_flag<-grepl("privacy",FBI_APPLE$Contents, ignore.case=TRUE)
FBI_APPLE$hashtags<-as.character(hashtags)
FBI_APPLE$attags<-as.character(attags)
FBI_APPLE$urls<-as.character(urls)
FBI_APPLE$isRT<-as.character(rt_flag)
FBI_APPLE$About_Privacy<-as.character(Privacy_flag)
dim(FBI_APPLE)
write.csv(FBI_APPLE,"FBI_APPLE_full.csv",row.names = FALSE)



Ash1=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Ashley Madison/Ash1.csv",stringsAsFactors = FALSE)
Ash2=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Ashley Madison/Ash2.csv",stringsAsFactors = FALSE)
Ash3=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Ashley Madison/Ash3.csv",stringsAsFactors = FALSE)
Ash4=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Ashley Madison/Ash4.csv",stringsAsFactors = FALSE)
dim(Ash1)
dim(Ash2)
dim(Ash3)
dim(Ash4)
#FBI-APPLE_sample=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Scripts/FBI-APPLE_1000.csv",stringsAsFactors = FALSE)
Ash=rbind(Ash1,Ash2,Ash3,Ash4)
#dim(Ash_sample)
dim(Ash)
### Extracting Hashtags,@ and URLs into seperate columns.
library(stringr)
hashtag.regex <- regex("(?<=^|\\s)#\\S+")
attag.regex<-regex("(?<=^|\\s)@\\S+")
url.regex<-regex("http[^[:blank:]]+")
Ash$Contents=tolower(Ash$Contents)
hashtags <- str_extract_all(Ash$Contents, hashtag.regex)
attags<-str_extract_all(Ash$Contents, attag.regex)
urls<-str_extract_all(Ash$Contents, url.regex)
rt_flag <- grepl("^RT",Ash$Contents, ignore.case=TRUE)
Privacy_flag<-grepl("privacy",Ash$Contents, ignore.case=TRUE)
Ash$hashtags<-as.character(hashtags)
Ash$attags<-as.character(attags)
Ash$urls<-as.character(urls)
Ash$isRT<-as.character(rt_flag)
Ash$About_Privacy<-as.character(Privacy_flag)
dim(Ash)
write.csv(Ash,"Ash_full.csv",row.names = FALSE)



Celeb1=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Celeb photo hack/Celeb1.csv",stringsAsFactors = FALSE)
Celeb2=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Celeb photo hack/Celeb2.csv",stringsAsFactors = FALSE)
Celeb3=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Celeb photo hack/Celeb3.csv",stringsAsFactors = FALSE)
Celeb4=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Celeb photo hack/Celeb4.csv",stringsAsFactors = FALSE)
dim(Celeb1)
dim(Celeb2)
dim(Celeb3)
dim(Celeb4)
#FBI-APPLE_sample=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Scripts/FBI-APPLE_1000.csv",stringsAsFactors = FALSE)
Celeb=rbind(Celeb1,Celeb2,Celeb3,Celeb4)
#dim(Celeb_sample)
dim(Celeb)
### Extracting HCelebtags,@ and URLs into seperate columns.
library(stringr)
hashtag.regex <- regex("(?<=^|\\s)#\\S+")
attag.regex<-regex("(?<=^|\\s)@\\S+")
url.regex<-regex("http[^[:blank:]]+")
Celeb$Contents=tolower(Celeb$Contents)
hashtags <- str_extract_all(Celeb$Contents, hashtag.regex)
attags<-str_extract_all(Celeb$Contents, attag.regex)
urls<-str_extract_all(Celeb$Contents, url.regex)
rt_flag <- grepl("^RT",Celeb$Contents, ignore.case=TRUE)
Privacy_flag<-grepl("privacy",Celeb$Contents, ignore.case=TRUE)
Celeb$hashtags<-as.character(hashtags)
Celeb$attags<-as.character(attags)
Celeb$urls<-as.character(urls)
Celeb$isRT<-as.character(rt_flag)
Celeb$About_Privacy<-as.character(Privacy_flag)
dim(Celeb)
write.csv(Celeb,"Celeb_full.csv",row.names = FALSE)




Snow1=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Snowden/Snow1.csv",stringsAsFactors = FALSE)
Snow2=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Snowden/Snow2.csv",stringsAsFactors = FALSE)
Snow3=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Snowden/Snow3.csv",stringsAsFactors = FALSE)
Snow4=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Snowden/Snow4.csv",stringsAsFactors = FALSE)
dim(Snow1)
dim(Snow2)
dim(Snow3)
dim(Snow4)
#FBI-APPLE_sample=read.csv("C:/Users/Jay/Desktop/Prof.Mike/Scripts/FBI-APPLE_1000.csv",stringsAsFactors = FALSE)
Snow=rbind(Snow1,Snow2,Snow3,Snow4)
#dim(Snow_sample)
dim(Snow)
### Extracting HSnowtags,@ and URLs into seperate columns.
library(stringr)
hashtag.regex <- regex("(?<=^|\\s)#\\S+")
attag.regex<-regex("(?<=^|\\s)@\\S+")
url.regex<-regex("http[^[:blank:]]+")
Snow$Contents=tolower(Snow$Contents)
hashtags <- str_extract_all(Snow$Contents, hashtag.regex)
attags<-str_extract_all(Snow$Contents, attag.regex)
urls<-str_extract_all(Snow$Contents, url.regex)
rt_flag <- grepl("^RT",Snow$Contents, ignore.case=TRUE)
Privacy_flag<-grepl("privacy",Snow$Contents, ignore.case=TRUE)
Snow$hashtags<-as.character(hashtags)
Snow$attags<-as.character(attags)
Snow$urls<-as.character(urls)
Snow$isRT<-as.character(rt_flag)
Snow$About_Privacy<-as.character(Privacy_flag)
dim(Snow)
write.csv(Snow,"Snow_full.csv",row.names = FALSE)


